// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl58zQ4J5bsaYHBMbY5eIpjpZd7B0oTVM',
    appId: '1:1075173890462:web:c0a6ba8687887ea34a9e8f',
    messagingSenderId: '1075173890462',
    projectId: 'rosiva-24fa4',
    authDomain: 'rosiva-24fa4.firebaseapp.com',
    storageBucket: 'rosiva-24fa4.firebasestorage.app',
    measurementId: 'G-GKN3YPV0QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRO5OnSCIqeIRt-hyKANQwz9I0plu8TMQ',
    appId: '1:1075173890462:android:65f766344257a2144a9e8f',
    messagingSenderId: '1075173890462',
    projectId: 'rosiva-24fa4',
    storageBucket: 'rosiva-24fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwFNsiMhQ03OzHTWUKUiorc6WdQw3xIc',
    appId: '1:1075173890462:ios:3b3081d985e6a02f4a9e8f',
    messagingSenderId: '1075173890462',
    projectId: 'rosiva-24fa4',
    storageBucket: 'rosiva-24fa4.firebasestorage.app',
    iosBundleId: 'com.example.rosivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwFNsiMhQ03OzHTWUKUiorc6WdQw3xIc',
    appId: '1:1075173890462:ios:3b3081d985e6a02f4a9e8f',
    messagingSenderId: '1075173890462',
    projectId: 'rosiva-24fa4',
    storageBucket: 'rosiva-24fa4.firebasestorage.app',
    iosBundleId: 'com.example.rosivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl58zQ4J5bsaYHBMbY5eIpjpZd7B0oTVM',
    appId: '1:1075173890462:web:999dccd385a115974a9e8f',
    messagingSenderId: '1075173890462',
    projectId: 'rosiva-24fa4',
    authDomain: 'rosiva-24fa4.firebaseapp.com',
    storageBucket: 'rosiva-24fa4.firebasestorage.app',
    measurementId: 'G-XM1SG0B3RP',
  );
}
