-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
-keep class io.flutter.plugins.googlesignin.** { *; }
-keep class com.google.android.gms.auth.** { *; }
-keep class com.google.android.gms.common.** { *; }
-dontwarn com.google.android.gms.**
-dontwarn com.google.firebase.**
